version: '3.1'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      - BOT_USERNAME=${BOT_USERNAME}
      - BOT_TOKEN=${BOT_TOKEN}

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRES_USER=hitsbot
      - POSTGRES_PASSWORD=hitsbot
      - POSTGRES_DB=hitsbot

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"