bot:
  username: ${BOT_USERNAME}
  token: ${BOT_TOKEN}

system:
  max-thread-number: 4

in-time:
  host: https://intime.tsu.ru
  request-timeout-millis: 600000

spring:
  datasource:
    url: jdbc:postgresql://db:5432/hitsbot
    username: hitsbot
    password: hitsbot
    driver-class-name: org.postgresql.Driver
  flyway:
    url: jdbc:postgresql://db:5432/hitsbot
    password: hitsbot
    driver-class-name: org.postgresql.Driver
    user: hitsbot
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 8080

redis:
  host-name: redis
  port: 6379