bot:
  username: # put your username here
  token: # put your token here
  request-timeout-millis: 600000
spring:
  datasource:
    url: jdbc:postgresql://db:5432/hitsbot
    username: hitsbot
    password: hitsbot
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080