bot:
  username: ${BOT_USERNAME}
  token: ${BOT_TOKEN}
  request-timeout-millis: 600000
system:
  max-thread-number: 4
spring:
  datasource:
    url: jdbc:postgresql://db:5432/hitsbot
    username: hitsbot
    password: hitsbot
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
redis:
  host: redis
  port: 6379